"""Create a valid blank document of a requested kind (M5 item 16).

The design is the one ROADMAP item 16 names as the likely answer, and it is the
one shipped here: **blank templates as package data**. A few kilobytes each,
always valid, and dependency-free — creating a real ``.docx`` needs no
python-docx/openpyxl/python-pptx at runtime, no Office install, and no COM. The
templates live next to the code as package data (like ``skills_bundle/``) and are
regenerated by ``scripts/dev/build_document_templates.py`` so the opaque binaries
stay reviewable.

Four kinds carry real content and copy a template; three are trivially empty
(``.py``/``.txt``/``.md``). A ``.ipynb`` is a JSON document with the required
``nbformat`` skeleton, not a template zip — but it still ships as a file for the
same reason: the skeleton is content the format requires, not emptiness.

The write reuses the workspace jail: :meth:`Workspace.safe_path` answers "is this
inside the workspace?" and :meth:`Workspace.write_bytes` is the same atomic
tmp-then-replace every other write goes through. This service copies no workspace
root of its own — it is handed the live ``Workspace`` per call — so it owes no
``set_workspace_root`` and is not part of the switcher's coordination list.
"""

from __future__ import annotations

from importlib.resources import files
from pathlib import Path

import structlog

from workbench_server.models.documents import DocumentKind
from workbench_server.services.workspace import Workspace

log = structlog.get_logger()

_TEMPLATE_PACKAGE = "workbench_server"
_TEMPLATE_DIR = "document_templates"

#: Kinds whose blank form is a real document copied from a bundled template.
_TEMPLATE_KINDS: frozenset[str] = frozenset({"docx", "xlsx", "pptx", "ipynb"})
#: Kinds whose blank form is an empty file with the right extension.
_EMPTY_KINDS: frozenset[str] = frozenset({"py", "txt", "md"})


class DocumentExtensionError(ValueError):
    """The path's extension does not match the requested kind.

    A guard against the one footgun the feature could otherwise create: writing
    ``.docx`` bytes to a ``foo.txt`` path. The UI always appends the right
    extension, so this only ever fires on a malformed direct call.
    """


class TemplateUnavailableError(RuntimeError):
    """A template kind was requested but the bundled templates are not on disk.

    Degraded, not fatal to the server: only *this* create fails, and it fails
    loudly rather than writing a corrupt document.
    """


class DocumentService:
    """Template provider + document writer. Stateless across workspaces."""

    def __init__(self) -> None:
        self._templates = _templates_dir()

    def blank_bytes(self, kind: DocumentKind) -> bytes:
        """The bytes of a valid blank document of this kind.

        Empty kinds return ``b""``; template kinds read the bundled file fresh
        (a few KB — no cache to go stale). Raises
        :class:`TemplateUnavailableError` if a template is needed but missing.
        """
        if kind in _EMPTY_KINDS:
            return b""
        if kind not in _TEMPLATE_KINDS:  # pragma: no cover - Literal guards the wire
            raise ValueError(f"unknown document kind: {kind}")
        if self._templates is None:
            raise TemplateUnavailableError(kind)
        template = self._templates / f"blank.{kind}"
        if not template.is_file():
            raise TemplateUnavailableError(kind)
        return template.read_bytes()

    def create(self, workspace: Workspace, relative: str, kind: DocumentKind) -> str:
        """Write a blank ``kind`` document at ``relative``. Returns its hash.

        Raises :class:`~workbench_server.services.workspace.PathOutsideWorkspaceError`
        for a path outside the jail, :class:`FileExistsError` if something is
        already there (a create never overwrites), :class:`DocumentExtensionError`
        on an extension/kind mismatch, and :class:`TemplateUnavailableError` if a
        needed template is missing.
        """
        if not relative.lower().endswith(f".{kind}"):
            raise DocumentExtensionError(f"{relative} does not end with .{kind}")
        # safe_path is the jail question, asked before anything is written.
        path = workspace.safe_path(relative)
        if path.exists():
            raise FileExistsError(relative)
        data = self.blank_bytes(kind)
        # write_bytes re-runs safe_path and does the atomic tmp-then-replace.
        return workspace.write_bytes(relative, data)


def _templates_dir() -> Path | None:
    """Absolute path of the bundled templates directory, or ``None`` if unusable.

    ``None`` (with a warning) when the package is installed in a form with no real
    filesystem path, such as a zipimport. Empty-kind creation still works; a
    template kind then fails loudly per call rather than silently.
    """
    resource = files(_TEMPLATE_PACKAGE) / _TEMPLATE_DIR
    if not isinstance(resource, Path):  # pragma: no cover - only under zipimport
        log.warning("document_templates.not_on_disk", resource=str(resource))
        return None
    if not resource.is_dir():  # pragma: no cover - packaging regression
        log.warning("document_templates.missing", path=str(resource))
        return None
    return resource
